"""canonical sqlite schema baseline

Revision ID: b9023bb6dd2f
Revises: 
Create Date: 2026-02-24 13:09:02.631641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9023bb6dd2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index('ix_accounts_currency', 'accounts', ['currency'], unique=False)
    op.create_index('ix_accounts_type', 'accounts', ['type'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_flag', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_categories_parent_id_name')
    )
    op.create_table('goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('monthly_contribution', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('spending_reduces_progress', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_table('import_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('source_fingerprint', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('source_fingerprint', 'source_type', name='uq_import_batches_source_fingerprint_source_type')
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants')),
    sa.UniqueConstraint('canonical_name', name='uq_merchants_canonical_name')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('review_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('ref_table', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items'))
    )
    op.create_index('ix_review_items_confidence', 'review_items', ['confidence'], unique=False)
    op.create_index('ix_review_items_status_item_type', 'review_items', ['status', 'item_type'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('apply_to_pending', sa.Boolean(), nullable=False),
    sa.Column('matcher_json', sa.JSON(), nullable=False),
    sa.Column('action_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index('ix_rules_enabled_priority', 'rules', ['enabled', 'priority'], unique=False)
    op.create_table('run_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('code_version', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('diagnostics_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_metadata'))
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name='uq_tags_name')
    )
    op.create_table('budget_buckets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('period_month', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rollover_policy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_budget_buckets_budget_id_budgets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_buckets'))
    )
    op.create_table('budget_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('policy_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_budget_categories_budget_id_budgets')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_budget_categories_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_categories'))
    )
    op.create_table('budget_periods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('period_month', sa.String(), nullable=False),
    sa.Column('to_assign', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('assigned_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('spent_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rollover_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_budget_periods_budget_id_budgets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_periods')),
    sa.UniqueConstraint('budget_id', 'period_month', name='uq_budget_periods_budget_id_period_month')
    )
    op.create_table('budget_rollovers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('dimension_type', sa.String(), nullable=False),
    sa.Column('dimension_id', sa.String(), nullable=False),
    sa.Column('from_period', sa.String(), nullable=False),
    sa.Column('to_period', sa.String(), nullable=False),
    sa.Column('carry_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('policy_applied', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_budget_rollovers_budget_id_budgets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_rollovers'))
    )
    op.create_table('goal_allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('period_month', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_goal_allocations_account_id_accounts')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_allocations_goal_id_goals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_allocations'))
    )
    op.create_table('merchant_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('source_context', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_aliases_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_aliases')),
    sa.UniqueConstraint('alias', 'source_context', name='uq_merchant_aliases_alias_source_context')
    )
    op.create_table('raw_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_raw_transactions_import_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_transactions'))
    )
    op.create_index('ix_raw_transactions_import_batch_id', 'raw_transactions', ['import_batch_id'], unique=False)
    op.create_index('ix_raw_transactions_parse_status', 'raw_transactions', ['parse_status'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('expected_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('computed_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('match_rate', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_reconciliations_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliations'))
    )
    op.create_index('ix_reconciliations_account_id_period_end', 'reconciliations', ['account_id', 'period_end'], unique=False)
    op.create_index('ix_reconciliations_status', 'reconciliations', ['status'], unique=False)
    op.create_table('recurrings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('interval_n', sa.Integer(), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('tolerance_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_recurrings_category_id_categories')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_recurrings_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurrings'))
    )
    op.create_table('rule_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('run_mode', sa.String(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_runs_rule_id_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_runs'))
    )
    op.create_table('statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_fingerprint', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('ending_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('diagnostics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_statements_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statements')),
    sa.UniqueConstraint('source_fingerprint', name='uq_statements_source_fingerprint')
    )
    op.create_index('ix_statements_account_id_period_end', 'statements', ['account_id', 'period_end'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('original_currency', sa.String(), nullable=True),
    sa.Column('pending_status', sa.String(), nullable=False),
    sa.Column('original_statement', sa.Text(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('source_transaction_id', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('transfer_group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_transactions_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_transactions_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index('ix_transactions_account_id_posted_date', 'transactions', ['account_id', 'posted_date'], unique=False)
    op.create_index('ix_transactions_category_id', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_merchant_id', 'transactions', ['merchant_id'], unique=False)
    op.create_index('ix_transactions_pending_status', 'transactions', ['pending_status'], unique=False)
    op.create_index('ux_transactions_account_source_kind_source_transaction_id_not_null', 'transactions', ['account_id', 'source_kind', 'source_transaction_id'], unique=True, sqlite_where=sa.text('source_transaction_id IS NOT NULL'))
    op.create_table('balance_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('statement_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_balance_snapshots_account_id_accounts')),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_balance_snapshots_statement_id_statements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_snapshots')),
    sa.UniqueConstraint('account_id', 'snapshot_date', 'source', name='uq_balance_snapshots_account_id_snapshot_date_source')
    )
    op.create_table('budget_allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_period_id', sa.String(), nullable=False),
    sa.Column('budget_category_id', sa.String(), nullable=False),
    sa.Column('assigned_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['budget_category_id'], ['budget_categories.id'], name=op.f('fk_budget_allocations_budget_category_id_budget_categories')),
    sa.ForeignKeyConstraint(['budget_period_id'], ['budget_periods.id'], name=op.f('fk_budget_allocations_budget_period_id_budget_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_allocations'))
    )
    op.create_table('budget_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_category_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cadence', sa.String(), nullable=True),
    sa.Column('top_up', sa.Boolean(), nullable=True),
    sa.Column('snoozed_until', sa.Date(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['budget_category_id'], ['budget_categories.id'], name=op.f('fk_budget_targets_budget_category_id_budget_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_targets'))
    )
    op.create_table('dedupe_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('txn_a_id', sa.String(), nullable=False),
    sa.Column('txn_b_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reason_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['txn_a_id'], ['transactions.id'], name=op.f('fk_dedupe_candidates_txn_a_id_transactions')),
    sa.ForeignKeyConstraint(['txn_b_id'], ['transactions.id'], name=op.f('fk_dedupe_candidates_txn_b_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dedupe_candidates'))
    )
    op.create_index('ix_dedupe_candidates_decision', 'dedupe_candidates', ['decision'], unique=False)
    op.create_index('ix_dedupe_candidates_score', 'dedupe_candidates', ['score'], unique=False)
    op.create_table('goal_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('related_transaction_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_events_goal_id_goals')),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id'], name=op.f('fk_goal_events_related_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_events'))
    )
    op.create_table('recurring_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recurring_id', sa.String(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('observed_transaction_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['observed_transaction_id'], ['transactions.id'], name=op.f('fk_recurring_events_observed_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurrings.id'], name=op.f('fk_recurring_events_recurring_id_recurrings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_events'))
    )
    op.create_table('rule_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_run_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rule_run_id'], ['rule_runs.id'], name=op.f('fk_rule_audits_rule_run_id_rule_runs')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_rule_audits_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_audits'))
    )
    op.create_index('ix_rule_audits_rule_run_id', 'rule_audits', ['rule_run_id'], unique=False)
    op.create_index('ix_rule_audits_transaction_id', 'rule_audits', ['transaction_id'], unique=False)
    op.create_table('transaction_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_events_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_events'))
    )
    op.create_index('ix_transaction_events_event_type', 'transaction_events', ['event_type'], unique=False)
    op.create_index('ix_transaction_events_transaction_id_created_at', 'transaction_events', ['transaction_id', 'created_at'], unique=False)
    op.create_table('transaction_splits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transaction_splits_category_id_categories')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_transaction_splits_goal_id_goals')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_splits_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_splits'))
    )
    op.create_index('ix_transaction_splits_transaction_id', 'transaction_splits', ['transaction_id'], unique=False)
    op.create_table('transaction_tags',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_transaction_tags_tag_id_tags')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_tags_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name=op.f('pk_transaction_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tags')
    op.drop_index('ix_transaction_splits_transaction_id', table_name='transaction_splits')
    op.drop_table('transaction_splits')
    op.drop_index('ix_transaction_events_transaction_id_created_at', table_name='transaction_events')
    op.drop_index('ix_transaction_events_event_type', table_name='transaction_events')
    op.drop_table('transaction_events')
    op.drop_index('ix_rule_audits_transaction_id', table_name='rule_audits')
    op.drop_index('ix_rule_audits_rule_run_id', table_name='rule_audits')
    op.drop_table('rule_audits')
    op.drop_table('recurring_events')
    op.drop_table('goal_events')
    op.drop_index('ix_dedupe_candidates_score', table_name='dedupe_candidates')
    op.drop_index('ix_dedupe_candidates_decision', table_name='dedupe_candidates')
    op.drop_table('dedupe_candidates')
    op.drop_table('budget_targets')
    op.drop_table('budget_allocations')
    op.drop_table('balance_snapshots')
    op.drop_index('ux_transactions_account_source_kind_source_transaction_id_not_null', table_name='transactions', sqlite_where=sa.text('source_transaction_id IS NOT NULL'))
    op.drop_index('ix_transactions_pending_status', table_name='transactions')
    op.drop_index('ix_transactions_merchant_id', table_name='transactions')
    op.drop_index('ix_transactions_category_id', table_name='transactions')
    op.drop_index('ix_transactions_account_id_posted_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_statements_account_id_period_end', table_name='statements')
    op.drop_table('statements')
    op.drop_table('rule_runs')
    op.drop_table('recurrings')
    op.drop_index('ix_reconciliations_status', table_name='reconciliations')
    op.drop_index('ix_reconciliations_account_id_period_end', table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index('ix_raw_transactions_parse_status', table_name='raw_transactions')
    op.drop_index('ix_raw_transactions_import_batch_id', table_name='raw_transactions')
    op.drop_table('raw_transactions')
    op.drop_table('merchant_aliases')
    op.drop_table('goal_allocations')
    op.drop_table('budget_rollovers')
    op.drop_table('budget_periods')
    op.drop_table('budget_categories')
    op.drop_table('budget_buckets')
    op.drop_table('tags')
    op.drop_table('run_metadata')
    op.drop_index('ix_rules_enabled_priority', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_review_items_status_item_type', table_name='review_items')
    op.drop_index('ix_review_items_confidence', table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('reports')
    op.drop_table('merchants')
    op.drop_table('import_batches')
    op.drop_table('goals')
    op.drop_table('categories')
    op.drop_table('budgets')
    op.drop_index('ix_accounts_type', table_name='accounts')
    op.drop_index('ix_accounts_currency', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
